name: toribash_bot
description: "Library for creating Toribash bots"
version: 1.0.0
homepage: "https://helgesverre.com"
author: "Helge Sverre <email@helgesverre.com>"
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  crypto: ^2.1.1+1